### PR TITLE
Add section about Issue Tracker Hygiene 

### LINKED ISSUE #34: Issue Tracker Hygiene
Split from #7 

https://github.com/morganey-lang/Morganey/pull/243#issuecomment-251353439

### PR DESCRIPTION
**Pull request by rexim**
Close #34

### CODE REVIEW

**Comment by ForNeVeR** [comment]
I'd expect a little more from this section: some general recommendations about what should be filed as an issue (refactoring tasks, any bugs, discussions (?)) and when (the sooner the better).

That's the first section about issue tracker in the document, so I suggest to describe general categories of issues that should be reported into the tracker.

**Review by ForNeVeR — DISMISSED** [review]
Regarding to this concrete statement added by this PR: LGTM.

**Comment by rexim** [comment]
@ForNeVeR good point. I'm gonna extend the section. Please dismiss your review.

**Comment by rexim** [comment]
Updated the PR. Issue categories are gonna be described in the scope of #21

**Comment by rexim** [comment]
@ForNeVeR please review again when you get a chance

**Review by ForNeVeR — APPROVED** [review]

**Comment by rexim** [comment]
@ForNeVeR thank you very much for the review!

**Pull request merged**
