### PR TITLE
README: remove WTFPL

### PR DESCRIPTION
**Pull request by ForNeVeR**
@Minoru says that WTFPL is not a good license because it makes no sense in Europe. I personally agree with that.

### CODE REVIEW

**Review by rexim — CHANGES_REQUESTED** [review]
Please, add a note that other Open Source license are negotiable.

**Comment by ForNeVeR** [comment]
@rexim I believe that's the separate case, see #30.

**Review by rexim — APPROVED** [review]

**Comment by rexim** [comment]
@ForNeVeR cool! Thanks for the changes.

**Comment by Minoru** [comment]
> @Minoru says that WTFPL is not a good license because it makes no sense in Europe.

I was merely quoting [OSI Board Meeting Minutes](https://opensource.org/minutes20090304):

> [WTFPL is] no different from dedication to the public domain. Author has submitted license approval request -- author is free to make public domain dedication. Although he agrees with the recommendation, **Mr. Michlmayr notes that public domain doesn't exist in Europe.**

**Pull request merged**
