### PR TITLE
Proofread README.md

### LINKED ISSUE #16: Proofread the rules
Second round: #18

Proofread the rules in [README.md](https://github.com/morganey-lang/community/blob/15e3e3d6d3f47ddc5a22de9fd1d1ac5080c3a02f/README.md) and submit the fixes and suggestions as a PR when you're ready.
- Assigned to @Minoru
- PR reviewers @rexim @Newlifer

### PR DESCRIPTION
**Pull request by Minoru**
Regarding punctuation in lists, see [this SE answer](http://english.stackexchange.com/a/75619/172834).

I tried to maintain the same form for all lists, that's why I changed things like "Leaving the community" to "Leave the community".

There's also a few tweaks to wording which, I hope, don't change the intended meaning.

---

Close #16

### CODE REVIEW

**Comment by rexim** [comment]
@Newlifer please provide your review of this PR when you get a chance. Thanks!

**Review by rexim — APPROVED** [review]
LGMT :+1: Thank you very much for spending your time on this!

**Review by Newlifer — APPROVED** [review]
I second this!

**Comment by rexim** [comment]
Great!

@Minoru thanks for the proofreading!
@Newlifer thanks for the review!

**Comment by Newlifer** [comment]
@rexim thanks for!

**Comment by ForNeVeR** [comment]
@Newlifer for!

**Pull request merged**
